name: Continuous Integration
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install prerequisites
      run: sudo apt update && sudo apt install curl cabextract libudev-dev
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Make (debug)
      run: make clean && make BUILD=DEBUG
    - name: Make (release)
      run: make clean && make BUILD=RELEASE
